UNSEEN -> LEARNING
LEARNING -> PRACTICING
PRACTICING -> MASTERED
MASTERED -> DECAYING

UNSEEN: {
  style.fill: "#EEF2F7"
}

MASTERED: {
  style.font-size: 15
}

DECAYING: {
  style.fill: "#E8E6DC"
}

*.style: {
  fill: "transparent"
  font-color: "#141413"
  border-radius: 4
  stroke: "#6b6a64"
}
