// Command masteryunits generates the draft mastery-unit partition described in ADR-046's D3,
// and the review report that makes the proposed boundaries inspectable.
//
// The output is a DRAFT and is marked as one in the file it writes. It is data, not a migration:
// nothing about assessments, progression, storage or the dashboard exists here, because all of
// that depends on the boundary and on D4's pass threshold, neither of which is decided.
//
// Regeneration at a different band width:
//
//	go run ./cmd/masteryunits -band 2
//
// There is no band-width constant in the package by design. The width is a draft parameter, it
// is recorded in the JSON, and the validator reads it from there — so changing it is a
// regeneration rather than a code change, and a width nobody has chosen cannot hide in a
// constant that reads like policy.
package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"sort"
	"strings"

	"github.com/chuma-beep/mathua/internal/concepts"
)

func main() {
	band := flag.Int("band", 3, "draft band width: unit = (domain, floor(subdomainDepth / band))")
	out := flag.String("out", concepts.MasteryUnitsPath, "path for the generated partition")
	report := flag.String("report", "data/mastery_units.report.md", "path for the review report")
	flag.Parse()

	if err := run(*band, *out, *report); err != nil {
		fmt.Fprintf(os.Stderr, "FAIL: %v\n", err)
		os.Exit(1)
	}
}

func run(band int, outPath, reportPath string) error {
	dag, err := concepts.LoadDir("data/concepts")
	if err != nil {
		return err
	}
	mu, err := concepts.BuildMasteryUnitDraft(dag, band)
	if err != nil {
		return err
	}

	raw, err := json.MarshalIndent(mu, "", "  ")
	if err != nil {
		return err
	}
	if err := os.WriteFile(outPath, append(raw, '\n'), 0o644); err != nil {
		return fmt.Errorf("write %s: %w", outPath, err)
	}

	findings := concepts.ValidateMasteryUnits(dag, mu)
	if err := writeReport(reportPath, dag, mu, findings); err != nil {
		return err
	}

	back := concepts.BackwardBandEdges(mu, dag)
	fmt.Printf("masteryunits: band width %d -> %d units over %d concepts\n",
		band, mu.UnitCount, mu.ConceptCount)
	fmt.Printf("  %s (%d)\n", outPath, len(raw))
	fmt.Printf("  %s\n", reportPath)
	fmt.Printf("  backward band edges: %d (surfaced, not corrected)\n", len(back))
	for _, f := range concepts.Anomalies(findings) {
		fmt.Printf("  anomaly: %s: %s\n", f.Kind, f.Detail)
	}
	if errs := concepts.Errors(findings); len(errs) > 0 {
		for _, f := range errs {
			fmt.Fprintf(os.Stderr, "  error: %s: %s\n", f.Kind, f.Detail)
		}
		return fmt.Errorf("%d partition error(s)", len(errs))
	}
	return nil
}

func sizesOf(mu *concepts.MasteryUnits) []int {
	out := make([]int, 0, len(mu.Units))
	for _, u := range mu.Units {
		out = append(out, u.ConceptCount)
	}
	sort.Ints(out)
	return out
}

func medianOf(sorted []int) int {
	if len(sorted) == 0 {
		return 0
	}
	return sorted[len(sorted)/2]
}

func countWhere(xs []int, pred func(int) bool) int {
	n := 0
	for _, v := range xs {
		if pred(v) {
			n++
		}
	}
	return n
}

func writeReport(path string, dag *concepts.DAG, mu *concepts.MasteryUnits, findings []concepts.Finding) error {
	sizes := make([]int, 0, len(mu.Units))
	for _, u := range mu.Units {
		sizes = append(sizes, u.ConceptCount)
	}
	sort.Ints(sizes)
	median := 0
	if len(sizes) > 0 {
		median = sizes[len(sizes)/2]
	}
	count := func(pred func(int) bool) int {
		n := 0
		for _, v := range sizes {
			if pred(v) {
				n++
			}
		}
		return n
	}

	edges, err := concepts.DerivedUnitPrereqs(mu, dag)
	if err != nil {
		return err
	}
	back := concepts.BackwardBandEdges(mu, dag)

	var b strings.Builder
	w := func(format string, args ...any) { fmt.Fprintf(&b, format+"\n", args...) }

	w("# Mastery units: draft boundary review")
	w("")
	w("Generated by `%s`. **This is a draft partition of the existing concept DAG, not a**", mu.GeneratedBy)
	w("**second hierarchy, and not an implementation of assessments.** Unit prerequisite order")
	w("below is *derived from the concept DAG*; it is not stored in the JSON.")
	w("")
	w("Rule: `%s`", mu.Rule)
	w("Band width: **%d** — a draft parameter. The open question is how often a learner should be", mu.BandWidth)
	w("assessed; `%d` is a candidate, not a decision. Regenerate with `-band 2` or `-band 4`.", mu.BandWidth)
	w("")
	w("## Size distribution")
	w("")
	w("| Metric | Value |")
	w("|---|---|")
	w("| Total concepts | %d |", mu.ConceptCount)
	w("| Total units | %d |", mu.UnitCount)
	w("| Minimum unit size | %d |", sizes[0])
	w("| Median unit size | %d |", median)
	w("| Maximum unit size | %d |", sizes[len(sizes)-1])
	w("| Singleton units | %d |", count(func(v int) bool { return v == 1 }))
	w("| Units with <= 3 concepts | %d |", count(func(v int) bool { return v <= 3 }))
	w("| Units with > 25 concepts | %d |", count(func(v int) bool { return v > 25 }))
	w("| Units with > 50 concepts | %d |", count(func(v int) bool { return v > 50 }))
	w("| Cross-unit prerequisite edges (derived) | %d |", len(edges))
	w("| Backward band edges | %d |", len(back))
	w("")
	w("If the learner is assessed once per unit, then %d assessments cover the corpus, and the", mu.UnitCount)
	w("median is one assessment per %d concepts. That is the frequency question this report", median)
	w("exists to make concrete.")
	w("")
	w("## Proposed units")
	w("")
	w("| Unit | Domain | Band | Concepts | Subdomains | Depth |")
	w("|---|---|---|---|---|---|")
	for _, u := range mu.Units {
		w("| `%s` | %s | %d | %d | %d | %d–%d |",
			u.ID, u.Domain, u.Band, u.ConceptCount, len(u.Subdomains), u.DepthMin, u.DepthMax)
	}
	w("")

	w("## Backward band edges")
	w("")
	if len(back) == 0 {
		w("None.")
	} else {
		w("%d prerequisite edges cross the unit ordering backwards, so the unit order is **not** a", len(back))
		w("topological order of the concept DAG. They are listed, not corrected.")
		w("")
		w("| Concept | Subdomain | Band | Needs | Prereq | Prereq subdomain | Prereq band | Same subdomain |")
		w("|---|---|---|---|---|---|---|---|")
		for _, e := range back {
			w("| `%s` | %s | %d | `%s` | `%s` | %s | %d | %v |",
				e.ConceptID, e.Subdomain, e.Band, e.PrereqID, e.PrereqID, e.PrereqSubdomain, e.PrereqBand, e.SameSubdomain)
		}
		w("")
		w("Every one of these is an artefact of measuring depth **per subdomain** rather than per")
		w("concept: see `docs/mastery-assessments.md` D3. A subdomain's level is set by its deepest")
		w("member, so a concept inside a deep subdomain can be a prerequisite of a concept inside a")
		w("shallower one. `concepts.ConceptDepths` computes the per-concept ranking instead, which")
		w("has zero backward edges by construction.")
	}
	w("")

	w("## Band width sweep")
	w("")
	w("The width is the open decision, so here is every candidate rather than one number. The")
	w("columns that matter are **singletons** (§12 forbids a quiz per concept) and **max**, since a")
	w("128-concept unit is not assessable either. Depth is per-concept here, so backward edges are 0")
	w("at every width.")
	w("")
	w("| Band width | Units | Median | Max | Singletons | <=3 | >25 | Backward |")
	w("|---|---|---|---|---|---|---|---|")
	for _, b := range []int{2, 3, 4, 5, 6, 8, 10, 12, 15, 20, 45} {
		trial, err := concepts.BuildMasteryUnitDraft(dag, b)
		if err != nil {
			continue
		}
		ss := sizesOf(trial)
		w("| %d | %d | %d | %d | %d | %d | %d | %d |", b, trial.UnitCount, medianOf(ss), ss[len(ss)-1],
			countWhere(ss, func(v int) bool { return v == 1 }),
			countWhere(ss, func(v int) bool { return v <= 3 }),
			countWhere(ss, func(v int) bool { return v > 25 }),
			len(concepts.BackwardBandEdges(trial, dag)))
	}
	w("")
	w("**No width is clean.** Small widths fragment — at %d there are %d singleton units, which is a", 3,
		countWhere(sizes, func(v int) bool { return v == 1 }))
	w("quiz per concept and is exactly what §12 rules out. Large widths stop fragmenting but produce")
	w("units too large to assess: at 45 the partition is just the 17 domains themselves, whose")
	w("largest is 128 concepts. The usable widths trade fragmentation against size rather than")
	w("resolving it, so")
	w("**this rule alone does not produce assessment-grade boundaries** and the partition needs hand")
	w("merging on top of a derived draft. That is the finding D3 was asked to produce.")
	w("")

	w("## Why depth is measured per concept")
	w("")
	_, _, unresolved := concepts.SubdomainDepths(dag)
	w("Banding on *subdomain* depth was the first candidate and it does not work on this corpus.")
	w("The subdomain condensation of the concept DAG **contains cycles**: grouping concepts by")
	w("subdomain discards the per-concept ordering, so a concept in subdomain A can be a")
	w("prerequisite of one in subdomain B whose other members depend on A.")
	w("")
	if len(unresolved) > 0 {
		w("**%d of 125 subdomains cannot be levelled** — they sit inside a cycle, or downstream", len(unresolved))
		w("of one, so no depth function exists for them at all. (Tarjan puts 26 inside cycles and")
		w("the remaining 34 behind them; Kahn cannot order either group, because ordering a node")
		w("requires its predecessors to be ordered first.) An implementation that ignores this")
		w("gets level 0 for all of them, which is a confidently wrong answer rather than a missing")
		w("one — which is what the first Go version of this generator did.")
		w("")
		w("Unresolvable subdomains:")
		w("")
		for i, s := range unresolved {
			if i > 0 && i%4 == 0 {
				w("")
			}
			w("`%s` ", s)
		}
		w("")
	} else {
		w("All subdomains resolved.")
	}
	w("Concept depth is a proper topological ranking on an acyclic graph, so it resolves all 657")
	w("concepts and yields zero backward band edges by construction.")
	w("")

	w("## Validation findings")
	w("")
	if len(findings) == 0 {
		w("None.")
	} else {
		for _, f := range findings {
			w("- **%s** `%s`: %s", f.Severity, f.Kind, f.Detail)
		}
	}
	w("")

	w("## Not decided here")
	w("")
	w("- The band width, which is the assessment frequency.")
	w("- The pass threshold (D4): a fixed proportion correct, versus requiring the assessment's")
	w("  answers to clear `mastery.MasteryThreshold`. This report deliberately implies neither.")
	w("- Whether a unit of one concept is an error or a content judgement.")
	w("- Everything downstream: assessment storage, migrations, pass/fail, the progression gate,")
	w("  retake policy, and any dashboard change.")
	w("")

	if err := os.WriteFile(path, []byte(b.String()), 0o644); err != nil {
		return fmt.Errorf("write %s: %w", path, err)
	}
	return nil
}
