package grader

import (
	"encoding/json"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"testing"
)

// This file is the proof that MathLive's answer output survives Mathua's existing
// graders unchanged.
//
// The math editor does not grade. It hands the server a plain-text string, and the
// server grades that string with the same graders, in the same formats, it used
// before the editor existed. That is only safe if every shape MathLive can emit is
// one a grader can already read — which is what this asserts, against a recording
// of the real library (web/next-app/test/fixtures/mathlive-plain-text.json,
// regenerated by scripts/record-mathlive-corpus.mjs).
//
// The `normalized` mirror below is deliberately a second implementation of
// components/math/plainAnswer.ts rather than a shared one: the value of this test
// is that two independent implementations agree, and sharing the code would make
// that vacuous.

type mathliveCase struct {
	GradingType string `json:"gradingType"`
	Expected    string `json:"expected"`
	LaTeX       string `json:"latex"`
	Plain       string `json:"plain"`
}

type mathliveCorpus struct {
	MathliveVersion string         `json:"mathliveVersion"`
	Cases           []mathliveCase `json:"cases"`
}

var (
	mixedNumbersRE = regexp.MustCompile(`(-?\d+)\((\d+)\)/\((\d+)\)`)
	// A single token per side, mirroring plainAnswer.ts: wide enough for `(pi)/(2)`,
	// narrow enough to leave `(x + 1)/(y)` alone.
	fractionParensRE = regexp.MustCompile(`\((-?[A-Za-z0-9.]+)\)/\((-?[A-Za-z0-9.]+)\)`)
	nameSpacingRE    = regexp.MustCompile(`(?m)([\w)])\s+([(^])`)
	letterRunRE      = regexp.MustCompile(`[A-Za-z](?: [A-Za-z])+`)
	letterRunOffset  = regexp.MustCompile(`[A-Za-z]`)
	spaceRE          = regexp.MustCompile(` +`)
)

// normalized mirrors components/math/plainAnswer.ts `toPlainAnswer`.
//
// A second implementation on purpose: the value of this test is that two independent
// implementations agree, and sharing the code would make that vacuous. So the guard
// below is re-derived here rather than imported.
func normalized(s string) string {
	s = strings.ReplaceAll(s, "-:", "/")
	s = mixedNumbersRE.ReplaceAllString(s, "${1} ${2}/${3}")
	s = fractionParensRE.ReplaceAllString(s, "${1}/${2}")
	s = nameSpacingRE.ReplaceAllString(s, "")
	return collapseLetterRuns(s)
}

// collapseLetterRuns rejoins a word MathLive split into single-letter factors.
//
// `yes` serialises as `y e s` and `addition` as `a d d i t i o n`, which never match
// the expected answer under the multiple-choice grader's exact comparison -- and those
// are the two most common expected answers in the corpus. The guard is what stops it
// eating real products: `2pi r` must survive, because collapsing it gives `2pir`.
func collapseLetterRuns(s string) string {
	return letterRunRE.ReplaceAllStringFunc(s, func(run string) string {
		start := strings.Index(s, run)
		if start < 0 {
			return run
		}
		// Extend left over the whole adjacent letter sequence, so the run inside
		// `2pi r` is understood as part of the product rather than a fresh word.
		for start > 0 && letterRunOffset.MatchString(s[start-1:start]) {
			start--
		}
		i := start - 1
		for i >= 0 && s[i] == ' ' {
			i--
		}
		if i >= 0 && !letterRunOffset.MatchString(s[i:i+1]) {
			return run
		}
		return spaceRE.ReplaceAllString(run, "")
	})
}

func loadMathliveCorpus(t *testing.T) mathliveCorpus {
	t.Helper()
	path := filepath.Join("..", "..", "web", "next-app", "test", "fixtures", "mathlive-plain-text.json")
	raw, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read corpus: %v", err)
	}
	var c mathliveCorpus
	if err := json.Unmarshal(raw, &c); err != nil {
		t.Fatalf("parse corpus: %v", err)
	}
	if len(c.Cases) == 0 {
		t.Fatal("corpus is empty; re-record it with scripts/record-mathlive-corpus.mjs")
	}
	return c
}

// pureGoTypes are the grading types decided without a subprocess, so their verdict
// is exact and cheap enough to assert in a bare `go test ./...`.
//
// SymPy-backed types (expression, symbolic, polynomial, complex) are excluded on
// purpose: gradeSymPy needs the pinned SymPy runtime, which is not guaranteed
// outside the image, and a Result.Unavailable would make the assertion vacuous.
// Those are covered by TestSympyGrade_ExpressionAndPolynomialBothRoute.
var pureGoTypes = map[GradingType]bool{
	GradingNumeric:        true,
	GradingTuple:          true,
	GradingOrdering:       true,
	GradingComparison:     true,
	GradingMultipleChoice: true,
}

// TestMathlivePlainTextGradesLikeTheGenerator asserts that an answer produced
// through the math editor grades the same as the same answer typed into the old
// plain input.
func TestMathlivePlainTextGradesLikeTheGenerator(t *testing.T) {
	r := NewRouter()
	defer r.Close()

	corpus := loadMathliveCorpus(t)

	checked := 0
	for _, c := range corpus.Cases {
		// `numeric-expression` rows are the documented limitation, asserted separately.
		if c.GradingType == "numeric-expression" {
			continue
		}
		gt := GradingType(c.GradingType)
		if !pureGoTypes[gt] {
			continue
		}
		checked++
		c := c
		answer := normalized(c.Plain)
		t.Run(c.GradingType+" "+c.LaTeX, func(t *testing.T) {
			got := r.Grade(gt, c.Expected, answer)
			if got.Unavailable {
				t.Fatalf("unavailable for %q: %s", answer, got.Feedback)
			}
			if !got.Correct {
				t.Errorf("expected %q, got %q\n  latex:      %s\n  raw plain:  %s\n  normalized: %s\n  feedback:   %s",
					c.Expected, answer, c.LaTeX, c.Plain, answer, got.Feedback)
			}
		})
	}

	if checked == 0 {
		t.Fatal("no pure-Go cases exercised; the corpus or pureGoTypes drifted apart")
	}
	t.Logf("graded %d/%d corpus cases through the pure-Go path", checked, len(corpus.Cases))
}

// TestMathliveNumericCannotEvaluatePinnedForms pins a known limitation rather than
// working around it.
//
// A learner who answers a `numeric` question by showing their working — 10^6,
// 12 × 4, 3.14 × 10^-2 — gets a string the numeric grader cannot evaluate, because
// parseNumeric accepts only a literal integer, decimal, n/d or mixed number. The
// verdict is "Could not parse numeric values": not a crash, not a crash of mastery,
// but a miss the learner cannot see the cause of.
//
// The math editor makes these easier to produce than the old plain input did,
// because it offers an exponent and a multiplication key. The arithmetic keyboard
// therefore keeps them (a learner must be able to type what they think) and the
// limitation is documented instead of silently transformed.
//
// If this test ever starts failing because the grade became *correct*, that is an
// improvement to note in the ADR, not a test to delete: evaluating a constant
// expression is exactly what a MathJSON-aware grader should do.
func TestMathliveNumericCannotEvaluatePinnedForms(t *testing.T) {
	r := NewRouter()
	defer r.Close()

	corpus := loadMathliveCorpus(t)

	found := 0
	for _, c := range corpus.Cases {
		if c.GradingType != "numeric-expression" {
			continue
		}
		found++
		c := c
		t.Run(c.LaTeX, func(t *testing.T) {
			got := r.Grade(GradingNumeric, c.Expected, normalized(c.Plain))
			if got.Unavailable {
				t.Fatalf("unavailable: %s", got.Feedback)
			}
			if got.Correct {
				t.Skipf("the numeric grader now evaluates %q; update docs/math-input.md", c.Plain)
			}
			if got.Feedback != "Could not parse numeric values" {
				t.Errorf("limitation moved: %q now fails as %q, not as a parse failure. Update the comment above and docs/math-input.md.", c.Plain, got.Feedback)
			}
		})
	}

	if found == 0 {
		t.Fatal("no numeric-expression cases in the corpus; the pinned limitation is untested")
	}
}

// TestMathliveNormalizationIsLoadBearing shows why toPlainAnswer exists.
//
// These are the raw strings MathLive emits. Fed to a grader unnormalized they are
// rejected, which is the false miss the editor would otherwise introduce on every
// fraction, mixed number and division.
func TestMathliveNormalizationIsLoadBearing(t *testing.T) {
	r := NewRouter()
	defer r.Close()

	cases := []struct {
		latex  string
		raw    string
		want   string
		graded bool
	}{
		{latex: `\frac{1}{2}`, raw: `(1)/(2)`, want: `1/2`, graded: true},
		{latex: `\frac{2}{4}`, raw: `(2)/(4)`, want: `2/4`, graded: true},
		{latex: `4\frac{1}{10}`, raw: `4(1)/(10)`, want: `4 1/10`, graded: true},
		{latex: `-1\frac{1}{2}`, raw: `-1(1)/(2)`, want: `-1 1/2`, graded: true},
		{latex: `7\div2`, raw: `7 -: 2`, want: `7 / 2`, graded: true},
	}

	for _, c := range cases {
		t.Run(c.latex, func(t *testing.T) {
			if got := normalized(c.raw); got != c.want {
				t.Fatalf("normalized(%q) = %q, want %q", c.raw, got, c.want)
			}
			if c.graded && r.Grade(GradingNumeric, "1/2", c.raw).Correct {
				t.Errorf("%q grades correct unnormalized; normalization is redundant for it", c.raw)
			}
		})
	}
}
