import type { LessonInfo } from '../../lib/api'
import conceptsData from '../../data/concepts.json'

type ConceptEntry = { id: string; label: string; domain: string }

export const conceptLabels = new Map<string, string>((conceptsData as ConceptEntry[]).map(c => [c.id, c.label]))

// ── Domain metadata ──────────────────────────────────────

export const domainOrder = [
  'arith', 'fractions', 'prealgebra',
  'alg', 'trig', 'calc', 'calc.integral', 'calc.deriv', 'calc.limit',
  'linalg', 'linalg.vector', 'linalg.matrix', 'linalg.eigen', 'linalg.det',
  'linalg.transformations', 'linalg.span', 'linalg.basis',
  'complex', 'complex.concept',
  'alg.poly', 'alg.factor', 'alg.quad', 'alg.log', 'alg.systems',
  'arith.exp', 'arith.sqrt',
  'abstract', 'abstract.group', 'abstract.ring', 'abstract.rings', 'abstract.homomorphism', 'abstract.structures', 'abstract.subgroup',
  'discrete', 'discrete.sets', 'discrete.combinatorics', 'discrete.graphs', 'discrete.induction', 'discrete.logic', 'discrete.proof', 'discrete.recurrence',
  'fractions', 'frac.add', 'frac.benchmark', 'frac.compare', 'frac.concept', 'frac.div', 'frac.equivalent', 'frac.mixed', 'frac.mult', 'frac.on_number_line', 'frac.parts', 'frac.simplify', 'frac.sub', 'frac.to_decimal',
  'geo', 'geo.basic', 'geo.circle', 'geo.coord', 'geo.quad', 'geo.solid', 'geo.triangle',
  'nt', 'nt.adv', 'nt.basics', 'nt.congruence', 'nt.crypto', 'nt.diophantine', 'nt.divisibility', 'nt.euler_phi', 'nt.fermat_little', 'nt.gcd_euclidean', 'nt.modular',
  'ode', 'ode.basics', 'ode.concept', 'ode.exact', 'ode.homogeneous', 'ode.laplace', 'ode.linear_first', 'ode.nonhomogeneous', 'ode.separable', 'ode.systems',
  'pct', 'pct.concept', 'pct.discount', 'pct.find_rate', 'pct.from_dec', 'pct.increase', 'pct.of_number', 'pct.tax_tip', 'pct.to_dec',
  'ratio', 'ratio.concept', 'ratio.proportion', 'ratio.rate', 'ratio.scale', 'ratio.simplify',
  'dec', 'dec.add', 'dec.compare', 'dec.div', 'dec.from_frac', 'dec.mult', 'dec.round', 'dec.sub', 'dec.to_frac',
  'stat', 'stat.adv', 'stat.data', 'stat.dist', 'stat.infer', 'stat.prob',
  'topo', 'topo.continuous', 'topo.metric', 'topo.open_closed',
  'ml', 'ml.backpropagation',
  'alg.conic', 'alg.eq', 'alg.exp', 'alg.func', 'alg.ineq', 'alg.linear', 'alg.seq',
  'arith.abs_value', 'arith.add', 'arith.dec', 'arith.div', 'arith.factor', 'arith.mult', 'arith.neg', 'arith.order_ops', 'arith.place', 'arith.round', 'arith.sci_notation', 'arith.sub',
  'calc.seq', 'calc.series',
  'complex.add_sub', 'complex.adv', 'complex.basics', 'complex.conjugate', 'complex.de_moivre', 'complex.divide', 'complex.mult', 'complex.ops', 'complex.polar', 'complex.roots',
  'linalg.cramer', 'linalg.lintrans', 'linalg.sys', 'linalg.systems', 'linalg.vec',
  'prealg.eq', 'prealg.expr', 'prealg.ineq', 'prealg.real', 'prealg.types', 'prealg.var',
  'trig.adv', 'trig.basics', 'trig.eq', 'trig.graph', 'trig.graph_cos', 'trig.graph_sin', 'trig.hyperbolic', 'trig.ident', 'trig.ineq', 'trig.inverse', 'trig.law_cosines', 'trig.law_sines', 'trig.period', 'trig.pythagorean_id', 'trig.radians', 'trig.reciprocal', 'trig.reference_angle', 'trig.sin_cos_def', 'trig.special_angles', 'trig.tan_def', 'trig.unit_circle',
]

export const domainLabels = {
  'arith': 'Arithmetic',
  'fractions': 'Fractions',
  'prealgebra': 'Pre-Algebra',
  'alg': 'Algebra',
  'trig': 'Trigonometry',
  'calc': 'Calculus',
  'calc.integral': 'Calculus · Integrals',
  'calc.deriv': 'Calculus · Derivatives',
  'calc.limit': 'Calculus · Limits',
  'linalg': 'Linear Algebra',
  'linalg.vector': 'Linear Algebra · Vectors',
  'linalg.matrix': 'Linear Algebra · Matrices',
  'linalg.eigen': 'Linear Algebra · Eigen',
  'linalg.det': 'Linear Algebra · Determinants',
  'linalg.transformations': 'Linear Algebra · Transformations',
  'linalg.span': 'Linear Algebra · Span',
  'linalg.basis': 'Linear Algebra · Basis',
  'complex': 'Complex Numbers',
  'complex.concept': 'Complex Numbers',
  'alg.poly': 'Algebra · Polynomials',
  'alg.factor': 'Algebra · Factoring',
  'alg.quad': 'Algebra · Quadratics',
  'alg.log': 'Algebra · Logarithms',
  'alg.systems': 'Algebra · Linear Systems',
  'arith.exp': 'Arithmetic · Exponents',
  'arith.sqrt': 'Arithmetic · Radicals',
  'abstract': 'Abstract Algebra',
  'abstract.group': 'Abstract Algebra · Groups',
  'abstract.ring': 'Abstract Algebra · Rings',
  'abstract.rings': 'Abstract Algebra · Rings',
  'abstract.homomorphism': 'Abstract Algebra · Homomorphisms',
  'abstract.structures': 'Abstract Algebra · Structures',
  'abstract.subgroup': 'Abstract Algebra · Subgroups',
  'discrete': 'Discrete Math',
  'discrete.sets': 'Discrete Math · Sets',
  'discrete.combinatorics': 'Discrete Math · Combinatorics',
  'discrete.graphs': 'Discrete Math · Graphs',
  'discrete.induction': 'Discrete Math · Induction',
  'discrete.logic': 'Discrete Math · Logic',
  'discrete.proof': 'Discrete Math · Proofs',
  'discrete.recurrence': 'Discrete Math · Recurrence',
  'frac.add': 'Fractions · Addition',
  'frac.benchmark': 'Fractions · Benchmark',
  'frac.compare': 'Fractions · Comparing',
  'frac.concept': 'Fractions · Concept',
  'frac.div': 'Fractions · Division',
  'frac.equivalent': 'Fractions · Equivalent',
  'frac.mixed': 'Fractions · Mixed Numbers',
  'frac.mult': 'Fractions · Multiplication',
  'frac.on_number_line': 'Fractions · Number Line',
  'frac.parts': 'Fractions · Parts of a Whole',
  'frac.simplify': 'Fractions · Simplifying',
  'frac.sub': 'Fractions · Subtraction',
  'frac.to_decimal': 'Fractions · to Decimal',
  'geo': 'Geometry',
  'geo.basic': 'Geometry · Basics',
  'geo.circle': 'Geometry · Circles',
  'geo.coord': 'Geometry · Coordinate',
  'geo.quad': 'Geometry · Quadrilaterals',
  'geo.solid': 'Geometry · Solids',
  'geo.triangle': 'Geometry · Triangles',
  'nt': 'Number Theory',
  'nt.adv': 'Number Theory · Advanced',
  'nt.basics': 'Number Theory · Basics',
  'nt.congruence': 'Number Theory · Congruence',
  'nt.crypto': 'Number Theory · Cryptography',
  'nt.diophantine': 'Number Theory · Diophantine Equations',
  'nt.divisibility': 'Number Theory · Divisibility',
  'nt.euler_phi': 'Number Theory · Euler\'s Totient',
  'nt.fermat_little': 'Number Theory · Fermat\'s Little Theorem',
  'nt.gcd_euclidean': 'Number Theory · GCD & Euclidean',
  'nt.modular': 'Number Theory · Modular Arithmetic',
  'ode': 'Differential Equations',
  'ode.basics': 'ODEs · Basics',
  'ode.concept': 'ODEs · Concept',
  'ode.exact': 'ODEs · Exact Equations',
  'ode.homogeneous': 'ODEs · Homogeneous',
  'ode.laplace': 'ODEs · Laplace Transform',
  'ode.linear_first': 'ODEs · First-Order Linear',
  'ode.nonhomogeneous': 'ODEs · Non-Homogeneous',
  'ode.separable': 'ODEs · Separable',
  'ode.systems': 'ODEs · Systems',
  'pct': 'Percentages',
  'pct.concept': 'Percentages · Concept',
  'pct.discount': 'Percentages · Discount',
  'pct.find_rate': 'Percentages · Find Rate',
  'pct.from_dec': 'Percentages · from Decimal',
  'pct.increase': 'Percentages · Increase',
  'pct.of_number': 'Percentages · of a Number',
  'pct.tax_tip': 'Percentages · Tax & Tip',
  'pct.to_dec': 'Percentages · to Decimal',
  'ratio': 'Ratios',
  'ratio.concept': 'Ratios · Concept',
  'ratio.proportion': 'Ratios · Proportion',
  'ratio.rate': 'Ratios · Rate',
  'ratio.scale': 'Ratios · Scale',
  'ratio.simplify': 'Ratios · Simplifying',
  'dec': 'Decimals',
  'dec.add': 'Decimals · Addition',
  'dec.compare': 'Decimals · Comparing',
  'dec.div': 'Decimals · Division',
  'dec.from_frac': 'Decimals · from Fractions',
  'dec.mult': 'Decimals · Multiplication',
  'dec.round': 'Decimals · Rounding',
  'dec.sub': 'Decimals · Subtraction',
  'dec.to_frac': 'Decimals · to Fractions',
  'stat': 'Statistics',
  'stat.adv': 'Statistics · Advanced',
  'stat.data': 'Statistics · Data',
  'stat.dist': 'Statistics · Distributions',
  'stat.infer': 'Statistics · Inference',
  'stat.prob': 'Statistics · Probability',
  'topo': 'Topology',
  'topo.continuous': 'Topology · Continuity',
  'topo.metric': 'Topology · Metric Spaces',
  'topo.open_closed': 'Topology · Open/Closed Sets',
  'ml': 'Machine Learning',
  'ml.backpropagation': 'ML · Backpropagation',
  'alg.conic': 'Algebra · Conic Sections',
  'alg.eq': 'Algebra · Equations',
  'alg.exp': 'Algebra · Exponents',
  'alg.func': 'Algebra · Functions',
  'alg.ineq': 'Algebra · Inequalities',
  'alg.linear': 'Algebra · Linear Equations',
  'alg.seq': 'Algebra · Sequences',
  'arith.abs_value': 'Arithmetic · Absolute Value',
  'arith.add': 'Arithmetic · Addition',
  'arith.dec': 'Arithmetic · Decimals',
  'arith.div': 'Arithmetic · Division',
  'arith.factor': 'Arithmetic · Factoring',
  'arith.mult': 'Arithmetic · Multiplication',
  'arith.neg': 'Arithmetic · Negatives',
  'arith.order_ops': 'Arithmetic · Order of Operations',
  'arith.place': 'Arithmetic · Place Value',
  'arith.round': 'Arithmetic · Rounding',
  'arith.sci_notation': 'Arithmetic · Scientific Notation',
  'arith.sub': 'Arithmetic · Subtraction',
  'calc.seq': 'Calculus · Sequences',
  'calc.series': 'Calculus · Series',
  'complex.add_sub': 'Complex · Add/Subtract',
  'complex.adv': 'Complex · Advanced',
  'complex.basics': 'Complex · Basics',
  'complex.conjugate': 'Complex · Conjugates',
  'complex.de_moivre': 'Complex · De Moivre',
  'complex.divide': 'Complex · Division',
  'complex.mult': 'Complex · Multiplication',
  'complex.ops': 'Complex · Operations',
  'complex.polar': 'Complex · Polar Form',
  'complex.roots': 'Complex · Roots',
  'linalg.cramer': 'Linear Algebra · Cramer\'s Rule',
  'linalg.vec': 'Linear Algebra · Vectors',
  'linalg.lintrans': 'Linear Algebra · Transformations',
  'linalg.sys': 'Linear Algebra · Systems',
  'linalg.systems': 'Linear Algebra · Systems',
  'prealg.eq': 'Pre-Algebra · Equations',
  'prealg.expr': 'Pre-Algebra · Expressions',
  'prealg.ineq': 'Pre-Algebra · Inequalities',
  'prealg.real': 'Pre-Algebra · Real Numbers',
  'prealg.types': 'Pre-Algebra · Number Types',
  'prealg.var': 'Pre-Algebra · Variables',
  'trig.adv': 'Trigonometry · Advanced',
  'trig.basics': 'Trigonometry · Basics',
  'trig.eq': 'Trigonometry · Equations',
  'trig.graph_cos': 'Trigonometry · Cosine Graphs',
  'trig.graph_sin': 'Trigonometry · Sine Graphs',
  'trig.hyperbolic': 'Trigonometry · Hyperbolic',
  'trig.ident': 'Trigonometry · Identities',
  'trig.ineq': 'Trigonometry · Inequalities',
  'trig.inverse': 'Trigonometry · Inverse',
  'trig.law_cosines': 'Trigonometry · Law of Cosines',
  'trig.law_sines': 'Trigonometry · Law of Sines',
  'trig.period': 'Trigonometry · Periodicity',
  'trig.pythagorean_id': 'Trigonometry · Pythagorean Identities',
  'trig.radians': 'Trigonometry · Radians',
  'trig.reciprocal': 'Trigonometry · Reciprocal',
  'trig.reference_angle': 'Trigonometry · Reference Angles',
  'trig.sin_cos_def': 'Trigonometry · Sine/Cosine Definitions',
  'trig.graph': 'Trigonometry · Graphs',
  'trig.special_angles': 'Trigonometry · Special Angles',
  'trig.tan_def': 'Trigonometry · Tangent Definition',
  'trig.unit_circle': 'Trigonometry · Unit Circle',
} satisfies Record<string, string>

export const domainIcons = {
  arith: '+',
  fractions: '½',
  frac: '½',
  prealgebra: '○',
  alg: 'x',
  trig: 'π',
  calc: '∫',
  'calc.integral': '∫',
  'calc.deriv': '∂',
  'calc.limit': '→',
  linalg: '⊕',
  complex: 'i',
  abstract: 'λ',
  discrete: '∈',
  nt: 'ℤ',
  geo: '△',
  ode: '∵',
  pct: '%',
  ratio: ':',
  dec: '.',
  stat: 'Σ',
  topo: '○',
  ml: '✦',
} satisfies Record<string, string>

export function domainIcon(domain: string): string {
  const parts = domain.split('.')
  for (let i = parts.length; i > 0; i--) {
    const key = parts.slice(0, i).join('.')
    if (domainIcons[key]) return domainIcons[key]
  }
  return '◇'
}

export function lessonProgress(lesson: LessonInfo) {
  if (!lesson.progress) return { mastered: 0, total: lesson.concepts.length }
  let mastered = 0
  for (const cid of lesson.concepts) {
    const p = lesson.progress[cid]
    if (p && p.status === 'MASTERED') mastered++
  }
  return { mastered, total: lesson.concepts.length }
}
