// Precomputed React Flow (dagre) positions for the concept graph.
//
// Generated by scripts/build-flow-layout.mjs (npm run flow:build, also part
// of prebuild). Client-side dagre.layout on 657 nodes costs ~2.2s of
// main-thread time on first paint; importing this instead removes that cost.
// The component falls back to client-side dagre when this artifact does not
// cover every requested concept (e.g. a freshly added concept before a
// rebuild, or a page rendering a custom concept set).
import raw from '../data/flow.positions.json'

export type FlowPoint = { x: number; y: number }

type PositionRecord = Record<string, [number, number]>

function isPosition(value: unknown): value is [number, number] {
  return (
    Array.isArray(value) &&
    value.length === 2 &&
    typeof value[0] === 'number' &&
    typeof value[1] === 'number'
  )
}

// Validate at the boundary: a malformed artifact degrades to an empty map,
// which makes precomputedLayout return null so the caller recomputes with dagre.
const positions: PositionRecord = {}
for (const [id, value] of Object.entries(raw)) {
  if (isPosition(value)) positions[id] = value
}

/**
 * Map concept ids to positions, or null when the artifact is incomplete.
 * Returning null (rather than a partial map) lets the caller fall back to
 * dagre for the whole set, so no node is ever left at the origin.
 */
export function precomputedLayout(ids: Iterable<string>): Map<string, FlowPoint> | null {
  const out = new Map<string, FlowPoint>()
  for (const id of ids) {
    const p = positions[id]
    if (!p) return null
    out.set(id, { x: p[0], y: p[1] })
  }
  return out.size > 0 ? out : null
}
